AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'log/**/*'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

